### ISSUE TITLE
install script should let choose port for hmm

### ISSUE THREAD

**Issue by Homoran** [hobbyquaker/hmcon#1]
I just installed hm-con on a RPI2 with ioBroker. Thus port 8081 ist still used.
I'd do some testing, but how communicate?

**Comment by hobbyquaker** [comment]
bin mal so frei auf Deutsch zu antworten :-)
Schau mal in die Datei `/opt/hmcon/etc/hm-manager.json`
Nach dem editieren den hm-manager neu starten mit
`sudo /etc/init.d/hm-manager stop`
`sudo /etc/init.d/hm-manager start`  
Readme wird asap aktualisiert und Abfrage im hmcon-setup.sh bau ich bei Gelegenheit ein.

**Comment by Homoran** [comment]
Danke, ...aber
bei root@Hamster-Raspi:~# sudo /etc/init.d/hm-manager stop
kommt:
Usage: [start|stop|kill|restart|status]

ich musste ins Verzeichnis wechseln cd /etc/init.d/ und dort hm-manager stop aufrufen

...und jetzt:
connect RF (127.0.0.1:2001)
ECONNREFUSED

**Comment by hobbyquaker** [comment]
sollte mit version 0.8 gefixt sein, Abfrage des hm-manager webserver-ports hab ich auch eingebaut.

**Comment by Homoran** [comment]
Abfrage kommt zwar, wird auch bestätigt:

> Choose Homematic Manager webserver port [8081] 8099
> Homematic Manager listening on http://bananapi:8099/

ist jedoch unter :8081 zu öffnen

...und wieder die 3 ECONNREFUSED

> 2015/06/14 21:49:37.848 <Info> BidCoS-Service started
> 2015/06/14 21:49:37.851 <Info> XmlRpc Server is listening on TCP port 2001
> 2015/06/14 21:49:37.862 <Error> All USB-Interfaces are in use by other applications
> 2015/06/14 21:49:37.864 <Error> No BidCoS-Interface available
> 2015/06/14 21:49:37.864 <Warning> Error initializing interfaces

**Comment by hobbyquaker** [comment]
versuch mal das ganze verzeichnis /opt/hmcon zu löschen und dann nochmal hmcon-setup.sh (v0.10) auszuführen. Unter umständen musst vorher noch rfd und hm-manager von Hand killen. Möglicherweise schadet auch ein reboot nicht wegen der udev-rules.

**Comment by Homoran** [comment]
war eine flammneue Installation auf einem jungfräulichen Bananapi.
/opt/hmcon komplett gelöscht, dann reboot
./hmcon-setup v0.10 durchgeführt
hm-manager leiß sich weder unter :8099 noch :8081 aufrufen

Manuelles starten:

> root@bananapi:~# /etc/init.d/hm-manager start
> [ ok ] Starting hm-manager (via systemctl): hm-manager.service.
> root@bananapi:~# /etc/init.d/rfd start
> [ ok ] Starting rfd (via systemctl): rfd.service.
> root@bananapi:~# nano /opt/hmcon/var/log/rfd.log

half auch nicht
in der hm-manager.json ist der port 8099 eingetragen.

Nach wechsel in /etc/init.d/

> root@bananapi:/etc/init.d# hm-manager restart
> hm-manager daemon is not running
> Starting hm-manager daemon...
> hm-manager daemon started. PID: 706

läuft wenigstens der hm-manager

> root@bananapi:/etc/init.d# rfd restart

habe ich nicht hinbekommen.
scheint aber zu laufen.

Jetzt ist der hm-manager unter :8099 zu erreichen und die Kommunikation mit den Devices klappt.
Werde morgen nochmals neu aufsetzen und erneut testen
Gute Nacht

**Comment by Homoran** [comment]
Neuinstallation läuft durch, endet mit 

> Configuration files are located in /opt/hmcon/etc
> Logfiles are located in /opt/hmcon/var/log
> 
> Start rfd now (Y/n)?
> [ ok ] Starting rfd (via systemctl): rfd.service.
> 
> Start Homematic Manager now (Y/n)?
> Starting hm-manager daemon...
> hm-manager daemon started. PID: 920
> Homematic Manager listening on http://bananapi:8099/
> 
> Have Fun :)

HM-Manager ist nicht zu erreichen
in /opt/hmcon/etc/hm-manager.json ist der Port 8099 eingetragen

Der Versuch den hm-Manager neu zu starten zeigt an:

> root@bananapi:/etc/init.d# ./hm-manager stop
> [ ok ] Stopping hm-manager (via systemctl): hm-manager.service.
> root@bananapi:/etc/init.d# ./hm-manager start
> [ ok ] Starting hm-manager (via systemctl): hm-manager.service.

ist .service richtig?

der rfd.log zeigt wieder an

> 2015/06/15 09:39:14.373 <Info> BidCoS-Service started
> 2015/06/15 09:39:14.376 <Info> XmlRpc Server is listening on TCP port 2001
> 2015/06/15 09:39:14.387 <Error> All USB-Interfaces are in use by other applicat$
> 2015/06/15 09:39:14.389 <Error> No BidCoS-Interface available
> 2015/06/15 09:39:14.389 <Warning> Error initializing interfaces

top zeigt auch den hm-manager nicht an:

> 180 root      20   0       0      0      0 S   0.0  0.0   0:00.01 flush-179:0
> 28 root      20   0       0      0      0 S   0.0  0.0   0:00.00 fsnotify_mark
> 385 root      20   0    7172   3608    532 S   0.0  0.4   0:02.26 haveged
> 68 root      20   0       0      0      0 S   0.0  0.0   0:01.50 hdmi proc
> 72 root      20   0       0      0      0 S   0.0  0.0   0:00.00 jbd2/mmcblk0p1-
> 33 root      20   0       0      0      0 S   0.0  0.0   0:00.00 jfsCommit
> 34 root      20   0       0      0      0 S   0.0  0.0   0:00.00 jfsCommit
> 32 root      20   0       0      0      0 S   0.0  0.0   0:00.00 jfsIO
> 35 root      20   0       0      0      0 S   0.0  0.0   0:00.00 jfsSync
> 93 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kauditd
> 18 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kblockd

Tante G sagte mir probier mal:

> root@bananapi:/etc/init.d# ./hm-manager status -1
> ● hm-manager.service - LSB: Homematic Manager
>   Loaded: loaded (/etc/init.d/hm-manager)
>   Active: active (exited) since Mon 2015-06-15 10:42:25 CEST; 1min 31s ago
>  Process: 733 ExecStop=/etc/init.d/hm-manager stop (code=exited, status=0/SUCCESS)
>  Process: 739 ExecStart=/etc/init.d/hm-manager start (code=exited, status=0/SUCCESS)
> 
> Jun 15 10:42:25 bananapi sudo[742]: root : TTY=unknown ; PWD=/ ; USER=hmcon ; COMMAND=/opt/hmcon/node_modules/.bin/hm-manager start
> Jun 15 10:42:25 bananapi sudo[742]: pam_unix(sudo:session): session opened for user hmcon by (uid=0)
> Jun 15 10:42:25 bananapi hm-manager[739]: Starting hm-manager daemon...
> <b>Jun 15 10:42:25 bananapi hm-manager[739]: hm-manager daemon failed to start:  Failed to write pidfile (EACCES)</b>
> Jun 15 10:42:25 bananapi sudo[742]: pam_unix(sudo:session): session closed for user hmcon
> Jun 15 10:42:25 bananapi systemd[1]: Started LSB: Homematic Manager.

ein erneutes hmcon-setup scheiterte zuerst daran, dass diese Datei nicht mehr vorhanden war.
nochmals mit wget geladen, hmcon-setup ausgeführt, ohne /opt/hmcon zu löschen, bestehende rfd config behalten, hm-manager neu installiert - wieder port 8099 angegeben - läuft!

Edit: erste Installation anscheinend aus dem ORDNER /root, zweite aus dem root-Verzeichnis /

Setze nochmal neu auf ;-)

Ich verstehe es noch nicht, aber:
es muss einen reboot geben und es muss zweimal installiert werden, wobei es egal ist, ob der reboot nach der ersten oder zweiten Installation erfolgt.

Jedesmal frisch aufgesetzt als root aus dem Ordner /root:
procedere gemäß readme - hm-manager läuft nicht
hmcon-setup erneut durchgeführt, dabei
- rfd Install - Yes
- keep old config - Yes
- hm-manager install - y
- port geändert
  danach läuft es immer noch nicht
  dann reboot - läuft!

Oder:
procedere gemäß readme - hm-manager läuft nicht
reboot - läuft immer noch nicht
hmcon-setup erneut durchgeführt, dabei
- rfd Install - Yes
- keep old config - Yes
- hm-manager install - y
- port geändert
  danach läuft es!

**Comment by hobbyquaker** [comment]
https://github.com/hobbyquaker/hmcon/commit/d8a77a22ea06274d5b254bdbf4e50970777c053d
