### ISSUE TITLE
rfd.conf which one?

### ISSUE THREAD

**Issue by rddaz2013** [hobbyquaker/hmcon#10]
ResetFile = /dev/ccu2-ic200
or
ResetFile = /sys/class/gpio/gpio18/value

for the http://www.elv.de/homematic-funkmodul-fuer-raspberry-pi-bausatz.html

**Comment by hobbyquaker** [comment]
you need to use the gpio18 (see https://github.com/hobbyquaker/hmcon/blob/master/hmcon-setup.sh#L127)
