### ISSUE TITLE
Group "gpio" doesn't exist -> rfd can't write reset-pin of HM-MOD-RPI-PCB

### ISSUE THREAD

**Issue by ploebb** [hobbyquaker/hmcon#13]
When I installed hmcon, adding the user hmcon to group "gpio" failed, because there is no such group on my Raspberry Pi (RPI2B, Raspbian jessie).
Therefore the init of rdf fails because it can't write to the gpio-value file (no permission).
Also: this file is owned by user root, group root, so adding hmcon to the group "gpio" wouldn't solve this.

Google only brought up the tool gpio-admin in regards to the gpio-group. Do I have to install it?
If so, it would be nice, to add it to the dependencies/install it with the install-script.

Or is there another explanation for this issue?

Thanks,
Jonas

**Comment by hobbyquaker** [comment]
Warum das group add drin ist kann ich Dir gar nicht beantworten, gute Frage ;) Da ist wohl was halb-fertig liegen geblieben. Hab bisher nur mit USB und LAN Gateways getestet, werde die Geschichte mit der Raspi-Platine jetzt aber auch testen.
Ich würde ggü gpio-group lieber den Ansatz mit einer udev rule nehmen (siehe Antwort von "katalyst" hier https://www.raspberrypi.org/forums/viewtopic.php?t=9667&f=29). Ich schau ob ich die Tage dazu komm, ansonsten begrüße ich auch immer Pull Requests ;)
Grüße, Sebastian

**Comment by ploebb** [comment]
Das mit der gpio-group kommt wahrscheinlich daher, dass wohl eigentlich unter Raspian jessie schon eine udev-rule existieren sollte, die den GPIOs die Gruppe "gpio" zuordnet.
Diese Regel existiert bei mir aber nicht. Evtl. weil ich von wheezy auf jessie geupgradet habe(?)

Werde die Sache heute noch mal anschauen und die Regel wie in dem Link einbauen.
Vielleicht bekomme ich ja auch dein setup-script angepasst.

Ein Test mit root-Rechten gab dann aber noch ein anderes Problem. Mal sehen.

**Comment by hobbyquaker** [comment]
Kann bestätigen dass die Gruppe gpio unter Raspbian Jessie (eben frisch installiert) existiert. Müssten wir ein check einbauen ob die Gruppe da ist.

**Comment by ploebb** [comment]
Hab ich eingebaut.
Ich installiere auch grade mal ein frisches jessie und teste das bearbeitete Skript da.
Dabei schau ich auch gleich ob dort eine entsprechende udev-rule schon existiert. Dann müssen wir keine neue erstellen.

Aber das Modul läuft jetzt soweit bei mir. Der user musste nur noch in die "dialout" Gruppe um auf die serielle Schnittstelle zugreifen zu können.

Wenn ich das getestet habe schick ich dir nen pull-request.

**Comment by ploebb** [comment]
Ich habe noch 2-3 weitere Bugs gefunden. Werde die heute Abend oder Morgen beheben bzw. hier als issue anlegen.
Sieht soweit aber gut aus.

**Comment by hobbyquaker** [comment]
alles klar, danke schonmal :) hab noch paar issues angelegt was mir noch so einfiel, würde jetzt aber erstmal auf dein PR warten bevor ich was mach.

**Comment by ploebb** [comment]
Kein Problem. Ich hab morgen Zeit und setz mich noch mal dran. Werde den Schnipsel den du in raspi-config gefunden hast mal einbauen.
