### ISSUE TITLE
Reboot

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/hmcon#15]
Falls Reboot erforderlich am Ende Hinweis und Frage ob Reboot durchgeführt werden soll

**Comment by ploebb** [comment]
Würde ich möglichst vermeiden wollen. Bisher braucht es das noch nach dem deaktivieren der serial-Konsole fürs HM-MOD-RPI-PCB (schau ich mir morgen noch mal an).
Wenn wir das nicht anders hinbekommen muss es aber natürlich rein.

**Comment by hobbyquaker** [comment]
ich würde es so angehen wie in raspi-config auch, wir setzen eine ASK_TO_REBOOT Variable und am Ende wird falls die gesetzt ist der User gefragt ob Reboot durchgeführt werden soll.
