### ISSUE TITLE
node bei bedarf installieren?

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/hmcon#17]
von wo, welche version? /usr/local oder debian paket nutzen? 
für arm? https://github.com/nathanjohnson320/node_arm  
oder weglassen und dem user überlassen?

**Comment by ploebb** [comment]
Ja wäre ich dafür. Allerdings Frage ich mich, ob nicht die Installation von hmcon und hm-manager ein bisschen klarer getrennt werden sollte? Weil node.js wird ja nur für hm-manager gebraucht.
Evtl. eigenes Install-script für hm-manager?

Ansonsten habe ich node.js 5.x hier auf Raspbian Jessie über die offizielle Anleitung auf [nodejs.org](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) installiert.
Dabei wird deren repo registriert und dann nodejs mit apt-get installiert.

Hätte den Vorteil(/Nachteil?), dass es mit apt-get upgrade auch mit aktualisiert wird.
Habe keine Ahnung von Node.js und weiß nicht, ob es evtl. mal inkompatibel werden kann? (Deswegen das /Nachteil?)

**Comment by hobbyquaker** [comment]
Hab den Homematic-Manager mit integriert damit der User sich nicht selbst um die Config kümmern muss, aber im Endeffekt hast Du recht, man kann Hmcon und Homematic-Manager eigentlich getrennt betrachten, allerdings glaube ich aber auch dass es wenig Leute gibt bzw geben wird die Hmcon ohne den HM-Manager nutzen.

Dem HM-Manager "sollte" die Node-Version egal sein, alles >= 0.10 sollte gehen. Wenn es ein offizielles Node Repo gibt würde ich das auch bevorzugen, war mir bis eben noch nicht bekannt.

**Comment by ploebb** [comment]
Tja da hast du natürlich recht. Das mit der Config ist schon praktisch so.

Und nur fürs node-Installieren brauchts eigentlich kein eigenes Install-Script.
Wenn jemand hm-manager alleine installieren möchte, bekommt er es auch hin die zwei Zeilen Code aus der Anleitung zu kopieren. Müsste dann nur der Link in die readme.

Ins hmcon-script würde ich es aber mit aufnehmen.

**Comment by Homoran** [comment]
Mein (persönliches) Ziel ist hmcon + ioBroker + Funkmodul auf einem RasPi zu betreiben.
für ioBroker ist eh nodejs (im Moment 4.4.0) drauf. Damit läuft auch der HM-Manager.
Allerdings gibt es den auch als Adapter für ioBroker. Ich denke da sollte ich auch den nutzen.
Insgesamt finde ich aber das Rundumsorglospaket für ein gelungenes Konzept.
Node installiert nach
`curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
   sudo apt-get install -y nodejs`

**Comment by hobbyquaker** [comment]
hab grade festgestellt dass die Node Builds von nodesource.com auf RPI Model B nicht laufen "Illegal Instruction". Das Build von https://github.com/nathanjohnson320/node_arm geht auf dem uralt-Pi, der hängt aber immer ewig hinterher Updates zu liefern. Macht die Entscheidung ob - und von wo - wir Node automatisch installieren noch schwieriger...

**Comment by ploebb** [comment]
Habe gerade festgestellt, dass jessie schon mit nodejs 0.10.29 vorinstalliert kommt. Versucht man da das Paket von nathanjohnson zu installieren schlägt dass wegen einem Paket-Konflikt fehl.

Man könnte ja einfach 0.10.29 nutzen, aber leider ist npm nicht vorinstalliert -.-
Wie man npm alleine installiert habe ich noch nicht rausgefunden.

Eine Möglichkeit wäre wohl einfach die vor-kompilierten Binaries von https://nodejs.org/en/download/ zu benutzen, wo npm wohl dabei ist. Da gibt's auch welche für armv6 sprich Raspberry Pi 1.
Installation läuft wahrscheinlich dann "manuell" per kopieren in ein bin-Verzeichnis (?)

**Comment by ploebb** [comment]
Habe gerade ein bisschen getestet auf RPI1 Mod B, frisches Jessie   
- Vorinstalliertes Node 0.10.29 entfernt mit apt-get remove nodejs
- Die Befehle von [hier](https://blog.wia.io/installing-node-js-v4-0-0-on-a-raspberry-pi) kopiert um node.js zu "installieren" (lädt nur die Binaries und kopiert sie nach /usr/local/)

Daraufhin lief das aktuelle hmcon install script problemlos durch (npm braucht auf dem alten pi eewig) und nach einem reboot lief rfd und hm-manager auf Anhieb.

Vorteil bei der Methode: man muss "nur" die CPU-Architektur rausfinden und das richtige .tar-Paket laden und man hat die freie Versionsauswahl. Auf nodejs.org/dist gibt's ab 4.0.0 wohl immer auch die bins für ARMv6

Nachteil: man muss sich selbst drum kümmern, dass die richtige Version installiert wird. Ein Repo wäre da natürlich praktischer aber das nodesources-repo installiert auf armv6 ja wohl das falsche Package (für armv7 -> Illegal Instruction)

Irgendwie alles subobtimal.
Vielleicht ist es fürs erste das beste einfach in der Readme ein paar Links zu verschiedene Möglichkeiten der Installation zu geben und den user selbst machen zu lassen?

**Comment by hobbyquaker** [comment]
Seh ich auch so, ins Readme packen.
