### ISSUE TITLE
Nicht-interaktiver Modus für Standard-Setup

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/hmcon#19]
Raspbian Jessie, HM-MOD-RPI-PCB, rfd, hm-manager, kein hs485d - das ist denke ich das am häufigsten anzutreffende Setup, sollte mit einer Command-Line Option ohne weitere Rückfragen installiert werden können.

**Comment by hobbyquaker** [comment]
Nochmal Gedanken gemacht, eigentlich überflüssig das anzugehen. Dafür sollte ein .deb paketiert werden, das deaktivieren der seriellen Konsole, User anlegen etc lässt sich dann ja auch über post- und pre-inst Scripte erledigen.

**Comment by ploebb** [comment]
So ein .deb-Paket wäre natürlich komfortabel!
