### ISSUE TITLE
Zugriff auf gpio funktioniert nicht bei rfd start bei boot

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/hmcon#27]
wenn rfd beim booten gestartet wird meldet er
`<Error> CCU2CommController::init(): Init failed. Cannot reset coprocessor. (Hint: Cannot write reset)`
nach `/etc/init.d/rfd restart` funktioniert es dann. Vermute mal der startet zu früh (=vor udev?)

**Comment by hobbyquaker** [comment]
`# Required-Start:    $all` im init script hilft leider nicht.

**Comment by hobbyquaker** [comment]
ein `sleep 10` behebt das problem, das is aber echt unschön. Verstehe noch nicht so ganz wie systemd die init-scripte verwurstet.

**Comment by hobbyquaker** [comment]
Kann das Problem eigentlich jemand reproduzieren? Mir drängt sich die Vermutung auf dass das bei mir zu Tage tritt weil ich so nen uralten RPI Model B zum testen benutze...

**Comment by ploebb** [comment]
Hatte die letzte Version vom install-script auf einem frischen jessie getestet. Allerdings auf dem pi2. Da hat rdf beim Reboot problemlos gestartet.

Könnte es morgen auf einem pi1 noch mal probieren.

**Comment by ploebb** [comment]
Hattest du schon probiert das start script in einem höheren runlevel zu registrieren? Das "required: all" heißt wohl nur, dass es als letztes von allen start-skripten startet oder? Das kann aber ja auch schon im runlevel 2 sein.

**Comment by ploebb** [comment]
Habe jetzt das Ganze auf einem RPI1 Mod B mit frischem Jessie probiert und konnte da das Problem leider nicht reproduzieren.  rfd und hm-manager starten problemlos automatisch nach dem reboot.

Du könntest trotzdem einfach mal versuchen im Start-Script das default-Start-runlevel von `2 3 4 5` auf `3 4 5` zu stellen und mit `update-rc.d rfd defaults` neu zu registrieren.

So wie ich das verstanden habe, sollte der Pi auf jeden Fall immer mindestens bis in den 3ten runlevel booten. Habe das dann aber nicht weiter verfolgt.

Übrigens mit Wheezy auf dem RPI1 lief bei mir rfd überhaupt nicht. Das startet da scheinbar gar nicht, zumindest wird keine log-Datei angelegt.

**Comment by hobbyquaker** [comment]
hmm seltsam. Keine Ahnung was da bei mir schief läuft, aber dann schließ ich den Issue vorerst mal wenn das bei niemand anderem Auftritt.

**Comment by hobbyquaker** [comment]
Hab es eben getestet ihn aus runlevel 2 rauszunehmen, leider gleiches Verhalten.
