### ISSUE TITLE
Fehler beim Anlegen des Autostarts

### ISSUE THREAD

**Issue by Homoran** [hobbyquaker/hmcon#3]
Ich bekomme bei der Installation folgende Fehlermeldung:

``` code
install startscript /etc/init.d/hm-manager (Y/n)?
update-rc.d: using dependency based boot sequencing
insserv: script hm-manager: service skeleton already provided!
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
```

wieder die drei Fehlermeldungen
nach reboot läuft nichts

``` code
root@Test-Raspi2:~# sudo ./hmcon-setup.sh
sudo: ./hmcon-setup.sh: command not found
root@Test-Raspi2:~# chmod a+x hmcon-setup.sh
chmod: Zugriff auf „hmcon-setup.sh“ nicht möglich: Datei oder Verzeichnis nicht gefunden
```

**Comment by hobbyquaker** [comment]
sollte mit 0.8 gefixed sein.

**Comment by Homoran** [comment]
Fehlermeldungen kommen nicht mehr, Autostart kann ich im Moment nicht testen :(

**Comment by chriscohnen** [comment]
Hallo,

Ich hatte bei der Installation auf einem Raspberry PI 2 unter Debian Jessie folgendes Problem:
(hmcon-installer v0.11)
untar error bei der Installation vom hm-manager bei Ausführen des npm
dies lies sich mit einem
sudo npm cache clean
und Neuversuch beheben.
Könnten Sie im Installer als step adden.

System Info
pi@raspberrypi ~/hmcon-installer $ uname -a
Linux raspberrypi 4.1.17-v7+ #838 SMP Tue Feb 9 13:15:09 GMT 2016 armv7l GNU/Linux
pi@raspberrypi ~ $ node -v
v0.12.10

es gibt auch (zumindest bei mir) Probleme mit den Systemd Scripts
bei rfd klappt das gar nicht, kann den rfd nur per Hand starten dann geht's
als user pi per /opt/hmcon/bin/rfd -c -l 0 -f /opt/hmcon/etc/rfd.conf -d

> /etc/init.d/hm-manager , hier musste ich
> USER=root setzen, damit es nach dem Boot startet...
>  ok hm-manager, geht als hmcon user, fehlt nur noch rfd als hmcon

wie bekommt man raus was bei den init scripten das Problem ist ?
