### ISSUE TITLE
Git package needed

### ISSUE THREAD

**Issue by Homoran** [hobbyquaker/hmcon#6]
Habe es größenwahnsinnig mit anderer Distro (gentoo auf bananapi) getestet.
Da muss noch git installiert werden

da gibt es außerdem kein apt-get.

alle anderen issues ebenfalls

**Comment by hobbyquaker** [comment]
Ja, das ist nicht supported. Plane das ausschließlich für Debian basierte Distributionen (Ubuntu, Raspbian, ...), solche die ihr Paketmanagement mittels apt machen. Bin mal so frei den Issue daher gleich zu schließen.

**Comment by Homoran** [comment]
geht das nicht sonst mit wget?

**Comment by hobbyquaker** [comment]
Unter Gentoo müsste man sich um einiges selbst kümmern, andere Startscripte, automatische Installation der benötigten Libs und so weiter ist halt alles auf Debian ausgelegt. Hab aber natürlich nix dagegen wenn Du das setup-script für Gentoo anpasst, aber ich selbst werde das eher nicht tun :)
