### ISSUE TITLE
Allgem. Frage zu hmcon

### ISSUE THREAD

**Issue by fortschritt311** [hobbyquaker/hmcon#8]
Hi Leute. 
Schönes lightweight Projekt. Genau das was ich gesucht habe.
Nur habe ich mal eine Frage bezüglich dem Diensten rfd und hs485d.
Kann ich diese auch per XML::RPC ansprechen und mir die Daten bspw. per init schicken lassen, wie es bei der CCU ging?

Gruß Maik

**Comment by hobbyquaker** [comment]
Jap, exakt. Die Schnittstellenprozesse (rfd/hs485d) stellen eine XML-RPC und eine BIN-RPC Schnittstelle inkl. "init" zur Verfügung. Wenn möglich würde ich aber eher empfehlen BIN-RPC zu nutzen, hat deutlich weniger Overhead als XML-RPC und belastet die Schnittstellenprozesse nicht so sehr da sie sich das "teure" XML parsen sparen können.

Allerdings ist Hmcon noch nicht ganz fertig, die hs485d Unterstützung steht noch auf der Todo, stand heute müsstest den in Handarbeit in Betrieb nehmen. Auch das einspielen von CCU2-Backups ist noch nicht fertig, auch das muss man stand heute noch von Hand machen.

Grüße,
Sebastian

**Comment by fortschritt311** [comment]
Ok super. Habe meine Heizungssteuerung kompl. in Perl geschrieben. Aktuell nutze ich die XML-RPC Schnittstelle. Ich konnte aber kein BIN-RPC Modul für Perl finden. Ist diese Schnittstelle irgendwo dokumentiert?

Mit  "von Hand in Betrieb nehmen" meinst du das es noch kein Install Script gibt und das Init.d Script erstellt werden muss usw.... eben von Hand konfigurieren, oder ist die OCCU-Schnittstelle als solche noch nicht einsatzbereit?

Danke und Gruß
Maik

**Comment by hobbyquaker** [comment]
Du kannst natürlich auch XML-RPC weiter nutzen, funktionieren tut das genauso. BIN-RPC Implementierungen kenne ich nur in Javascript (https://github.com/hobbyquaker/binrpc), Java (https://github.com/owagner) und C++ (https://github.com/homegear).

Hmcon kann dir aktuell nur für den rfd (Funk) alles automatisch anlegen (init scripts, config etc), nicht für den hs485d (Wired). Beim hs485d gibt es auch noch das Problem dass es noch keine Command-Line Params für die Pfade zum config-file etc gibt, sprich Du wirst da mittels symlink die Dateien wie auf der CCU nachbilden müssen... Hab Issues dafür angelegt: https://github.com/eq-3/occu/issues/23 https://github.com/eq-3/occu/issues/24

**Comment by fortschritt311** [comment]
Danke für die Infos. Ich werd am WE erst mal den rfd in Betrieb nehmen. Hab den LAN Adapter hier noch wegen lxccu rumliegen. Wenn das funktioniert versuch ich mal den hs485d zum laufen zu bekommen, muss mir aber noch fix nen Wired-LAN-Interface besorgen.

Noch was : du hast ja bei EQ3 die Issues angelegt, ich hab da mal geschaut, da sind ja noch unbeantwortete vom Mai. Passiert da auch was, oder ist das die normale Wartezeit?

**Comment by hobbyquaker** [comment]
Kein Sorge, eQ-3 kümmert sich. Musst auch mal die geschlossenen Issues anschauen ;-)

**Comment by fortschritt311** [comment]
Ah jo, eben gesehen. Alles klar.
Danke für den Support. 

Gruß Maik
